version: "3.9"

services:

  config:
    image: config-server-swarm
    ports:
      - "8012:8012"
    networks:
      - cloud-backend-swarm

  discovery:
    image: discovery-swarm
    hostname: discovery
    ports:
      - "8089:8089"
    networks:
      - cloud-backend-swarm

  api-gateway:
    image: api-gateway-swarm
    depends_on:
      - discovery
      - config
    ports:
      - "8088:8088"
    networks:
      - cloud-backend-swarm
    deploy:
      replicas: 1

  travel:
    image: travel-swarm
    depends_on:
      - discovery
      - config
    networks:
      - cloud-backend-swarm
    deploy:
      replicas: 2

  user:
    image: user-swarm
    depends_on:
      - discovery
      - config
    ports:
      - "8869:8869"
    networks:
      - cloud-backend-swarm
    deploy:
      replicas: 2

networks:
  cloud-backend-swarm:
