version: "3.9"
name: cloud-project

services:

  config:
    build: ./config-server
    ports:
      - "8012:8012"
    networks:
      - cloud-backend
    healthcheck:
      test: "curl --fail --silent localhost:8012/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10

  discovery:
    hostname: discovery
    build: ./discovery
    ports:
      - "8089:8089"
      - "8761:8761"
    networks:
      - cloud-backend
    healthcheck:
      test: "curl --fail --silent localhost:8089/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10

  travel:
    build: ./travel-service
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
    networks:
      - cloud-backend

  user:
    build: ./user-service
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
    ports:
      - "8869:8869"
    networks:
      - cloud-backend

networks:
  cloud-backend:
