version: "3.9"
name: cloud-project

services:

  discovery:
    hostname: discovery
    build: ./discovery
    ports:
      - "8089:8089"
    networks:
      - cloud-backend
    healthcheck:
      test: "curl --fail --silent localhost:8089/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10

  travel:
    build: ./travel-service
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - "8090:8090"
    networks:
      - cloud-backend

  user:
    build: ./user-service
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - "8091:8091"
    networks:
      - cloud-backend

networks:
  cloud-backend:
