server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8089/eureka



logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: travel-service
          uri: lb://travel-service
          predicates:
            - Path=/travels/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**